### ISSUE TITLE
Prepare possible SHACL 1.2 work, splitting SHACL into Core and SPARQL documents

### ISSUE THREAD

**Issue by HolgerKnublauch** [w3c/shacl#26]
Since we have renewed interest in a new SHACL release, we could aim at preparing a new WG with the goal of updating SHACL to align it with RDF 1.2. To facilitate this, I suggest we split the main spec into Core and SPARQL Extensions. I am preparing a PR to get the ball rolling.

See https://drive.google.com/file/d/1m8A9tg5PSUxxac6f_DHbYQFed9uTqiNP/view for an ad hoc meeting that selected interested parties had on Feb 13 2024 to discuss a possible way forward.

**Comment by TallTed** [comment]
I have added your hour-long meeting video to my queue, but it will help me and likely others if some textual notes/logs/minutes could be attached here. For any future meetings, minutes/notes/logs will be *strongly* desired. (Does Google Meet offer any sort of transcription, perhaps?)

Please also notify me (and provide a way for others to request similar notification) of any future meetings, optimally using the [CG](https://www.w3.org/community/shacl/) mailing list and other available tools, optimally in advance but otherwise upon commencement.

I would also suggest that the current CG chairs (Irene and/or Simon) post something about the possibility of SHACL 1.2 to the CG blog and/or mailing list.

**Comment by HolgerKnublauch** [comment]
Hi Ted, yes my deep apologies. I should have clicked that checkbox to also produce a transcript for the Google Meet.

And yes, this was a one-off meeting and everything else will continue on the public mailing list and issue tracker.

**Comment by HolgerKnublauch** [comment]
With the announcement sent out https://lists.w3.org/Archives/Public/public-shacl/2024Feb/0000.html and the merge of #25 I consider this starting point done, and mark this as closed.

From here we can produce additional tickets for incremental steps.
