### ISSUE TITLE
SHACL-compact-syntax

### ISSUE THREAD

**Issue by jeswr** [w3c/shacl#7]
I've been looking into using shaclc in some applications I am working on. I have a couple of questions:

1. What are the chances of it becoming a standard (at the moment I understand it is a community group draft report) and are there any competing proposals.

2. What is available in terms of shaclc parsers? The only one I seem to have come across is that used in Topquadrant's SHACL API. Specifically I am looking for a parser in Javascript that can be used in applications licensed under the MIT license.

**Comment by afs** [comment]
Apache Jena [supports SHACL Compact Syntax](https://jena.apache.org/documentation/shacl/#shacl-compact-syntax) for both reading and writing. (not javascript)

**Comment by jeswr** [comment]
Thanks for letting me know.

I ended up implementing my own parser and writer in Typescript/JavaScript in a way that it would be possible to extend the syntax to cover all of SHACL by "escaping" into turtle, whilst also having the option to remain strictly compliant to the SHACLC spec.

I haven't had time to make the tools stable and publish them yet, but I'll add a comment here when I do.

**Comment by afs** [comment]
Sounds interesting - looking forward to seeing it.

I've had an idea to extend SHACLC with declarations for RDFS.

**Comment by VladimirAlexiev** [comment]
@afs what declarations do you mean?

As @HolgerKnublauch points out, you can put any triples in a "SHACL file" (because that's just RDF), and some of these are useful/relevant to the shapes as well.
- In particular, SHACL talks of `rdfs:subClassOf` (but AFAIK, not `domain, range, subPropertyOf`).
- In the TEKG project we use a lot of app-specific extensions: https://transparency.ontotext.com/spec/#describing-validation-rules (yes, I know that `sh:order, group` are supposed to be applied to `PropertyShape`, but we found it convenient to apply them to `NodeShape`)

So tacking a generic "RDF container" to SHACL seems like a good idea?

**Comment by afs** [comment]
<C1> subClassOf <C2>
<P1> subProprtyOf <P2>

**Comment by jeswr** [comment]
@afs almost 2 years late but finally got around to doing this up
1. https://www.npmjs.com/package/shaclc-parse; a spec compliant parser with an opt-in feature to use a superset of the syntax that allows you to "escape into turtle syntax".
2. https://www.npmjs.com/package/shaclc-write; a spec compliant writer.
